<?php
/**
 * Specificity build for plugin CSS on Avada sites.
 *
 * Avada's compiled stylesheet loads after plugin CSS and styles bare elements
 * (`.post-content h2`, `.fusion-body h4`). Every selector that starts with a
 * class gets that class repeated once (`.x-title` -> `.x-title.x-title`):
 * same elements, +1 class of specificity, relations between our own rules
 * unchanged. Handles @media, @supports and @container; leaves @keyframes and
 * @font-face alone.
 *
 *     php build-css.php assets/src/plugin.css assets/plugin.css
 */

[ , $in, $out ] = $argv + [ null, null, null ];
if ( ! $in || ! $out || ! is_readable( $in ) ) {
	fwrite( STDERR, "usage: php build-css.php <source.css> <output.css>\n" );
	exit( 1 );
}
$src = file_get_contents( $in );

function cl_bump_selector( $sel ) {
	$lead = strlen( $sel ) - strlen( ltrim( $sel ) );
	$body = ltrim( $sel );
	if ( preg_match( '/^\.([A-Za-z0-9_-]+)/', $body, $m ) ) {
		$body = '.' . $m[1] . $body;
	}
	return substr( $sel, 0, $lead ) . $body;
}

function cl_split_selectors( $list ) {
	$out   = [];
	$depth = 0;
	$cur   = '';
	foreach ( str_split( $list ) as $ch ) {
		if ( '(' === $ch ) {
			$depth++;
		} elseif ( ')' === $ch ) {
			$depth--;
		}
		if ( ',' === $ch && 0 === $depth ) {
			$out[] = $cur;
			$cur   = '';
			continue;
		}
		$cur .= $ch;
	}
	$out[] = $cur;
	return $out;
}

/** Walks a block of CSS; rewrites selectors of style rules. */
function cl_process( $css ) {
	$out = '';
	$len = strlen( $css );
	$i   = 0;
	while ( $i < $len ) {
		// Whitespace and comments pass through.
		if ( ctype_space( $css[ $i ] ) ) {
			$out .= $css[ $i++ ];
			continue;
		}
		if ( '/*' === substr( $css, $i, 2 ) ) {
			$end  = strpos( $css, '*/', $i + 2 );
			$end  = false === $end ? $len : $end + 2;
			$out .= substr( $css, $i, $end - $i );
			$i    = $end;
			continue;
		}
		$brace = strpos( $css, '{', $i );
		if ( false === $brace ) {
			$out .= substr( $css, $i );
			break;
		}
		// Find the matching closing brace.
		$depth = 0;
		for ( $j = $brace; $j < $len; $j++ ) {
			if ( '{' === $css[ $j ] ) {
				$depth++;
			} elseif ( '}' === $css[ $j ] ) {
				$depth--;
				if ( 0 === $depth ) {
					break;
				}
			}
		}
		$prelude = substr( $css, $i, $brace - $i );
		$inner   = substr( $css, $brace + 1, $j - $brace - 1 );
		$head    = ltrim( $prelude );
		if ( 0 === strpos( $head, '@media' ) || 0 === strpos( $head, '@supports' ) || 0 === strpos( $head, '@container' ) ) {
			$out .= $prelude . '{' . cl_process( $inner ) . '}';
		} elseif ( '@' === substr( $head, 0, 1 ) ) {
			$out .= $prelude . '{' . $inner . '}'; // @keyframes, @font-face: untouched.
		} else {
			// Keep any comment/whitespace before the selector list as is.
			$out .= implode( ',', array_map( 'cl_bump_selector', cl_split_selectors( $prelude ) ) ) . '{' . $inner . '}';
		}
		$i = $j + 1;
	}
	return $out;
}

$banner = '/* Generated by build-css.php from ' . basename( $in ) . " – do not edit. */\n";
file_put_contents( $out, $banner . cl_process( $src ) );
echo $out . " written\n";
