<?php
/**
 * Builds assets/piodesign.css from assets/src/piodesign.css.
 *
 * Avada's compiled stylesheet loads after ours and styles bare elements with
 * selectors such as `.post-content h2` or `.fusion-body h4`. To win without
 * !important, every selector that starts with a class gets that class
 * repeated once (`.pio-ev__title` -> `.pio-ev__title.pio-ev__title`). The
 * repeat matches exactly the same elements and adds one class of specificity,
 * so relations between our own rules stay the same.
 *
 *     php tools/build-css.php
 *
 * Edit only assets/src/piodesign.css.
 */

$root = dirname( __DIR__ );
$src  = file_get_contents( $root . '/assets/src/piodesign.css' );

function piodesign_bump_selector( $sel ) {
	$lead = strlen( $sel ) - strlen( ltrim( $sel ) );
	$body = ltrim( $sel );
	if ( preg_match( '/^\.([A-Za-z0-9_-]+)/', $body, $m ) ) {
		$body = '.' . $m[1] . $body;
	}
	return substr( $sel, 0, $lead ) . $body;
}

function piodesign_split_selectors( $list ) {
	$out   = [];
	$depth = 0;
	$cur   = '';
	foreach ( str_split( $list ) as $ch ) {
		if ( '(' === $ch ) {
			$depth++;
		} elseif ( ')' === $ch ) {
			$depth--;
		}
		if ( ',' === $ch && 0 === $depth ) {
			$out[] = $cur;
			$cur   = '';
			continue;
		}
		$cur .= $ch;
	}
	$out[] = $cur;
	return $out;
}

/** Walks a block of CSS; rewrites selectors of style rules. */
function piodesign_process( $css ) {
	$out = '';
	$len = strlen( $css );
	$i   = 0;
	while ( $i < $len ) {
		// Whitespace and comments pass through.
		if ( ctype_space( $css[ $i ] ) ) {
			$out .= $css[ $i++ ];
			continue;
		}
		if ( '/*' === substr( $css, $i, 2 ) ) {
			$end  = strpos( $css, '*/', $i + 2 );
			$end  = false === $end ? $len : $end + 2;
			$out .= substr( $css, $i, $end - $i );
			$i    = $end;
			continue;
		}
		$brace = strpos( $css, '{', $i );
		if ( false === $brace ) {
			$out .= substr( $css, $i );
			break;
		}
		// Find the matching closing brace.
		$depth = 0;
		for ( $j = $brace; $j < $len; $j++ ) {
			if ( '{' === $css[ $j ] ) {
				$depth++;
			} elseif ( '}' === $css[ $j ] ) {
				$depth--;
				if ( 0 === $depth ) {
					break;
				}
			}
		}
		$prelude = substr( $css, $i, $brace - $i );
		$inner   = substr( $css, $brace + 1, $j - $brace - 1 );
		$head    = ltrim( $prelude );
		if ( 0 === strpos( $head, '@media' ) || 0 === strpos( $head, '@supports' ) ) {
			$out .= $prelude . '{' . piodesign_process( $inner ) . '}';
		} elseif ( '@' === substr( $head, 0, 1 ) ) {
			$out .= $prelude . '{' . $inner . '}'; // @keyframes, @font-face: untouched.
		} else {
			// Keep any comment/whitespace before the selector list as is.
			$out .= implode( ',', array_map( 'piodesign_bump_selector', piodesign_split_selectors( $prelude ) ) ) . '{' . $inner . '}';
		}
		$i = $j + 1;
	}
	return $out;
}

$banner = "/* Generated by tools/build-css.php from assets/src/piodesign.css – do not edit. */\n";
file_put_contents( $root . '/assets/piodesign.css', $banner . piodesign_process( $src ) );
echo "assets/piodesign.css written\n";
